#!/usr/bin/env bash
# The environment a command needs to talk to the running stack (P194-01).
#
# ## Why this file exists
#
# `docker-compose.prod.yml` interpolates its variables from **three** sources,
# and `deploy.sh` assembles all three:
#
#   ~/ds-education/config.env    written by a human — BASE_DOMAIN, database
#                                name, the superuser's *name*
#   ~/ds-education/secrets.env   generated by secrets.sh, mode 600 — every
#                                password, SECRETS_KMS_KEY, BACKUP_ENCRYPTION_KEY
#   ds_derive_domains            computed, stored nowhere — every domain, and
#                                DS_SITES_DIR, which is a bind-mount path
#
# The third is the one that is easy to miss, because it is not a file somebody
# forgot: it is a function call. Deploy 119 got past the second and died on the
# third with `invalid spec: :/etc/caddy/sites:ro: empty section between
# colons` — an empty `${DS_SITES_DIR}` in the caddy service's volume list,
# reported while parsing, for a command that addressed postgres.
#
# Anything that loads only the first cannot run `docker compose` at all, and
# the way it fails is the reason this is a file rather than a line repeated in
# four places:
#
#     error while interpolating services.api.environment.SECRETS_KMS_KEY:
#     required variable SECRETS_KMS_KEY is missing a value
#
# `${SECRETS_KMS_KEY:?…}` makes compose abort **while parsing the file**, before
# it looks at which service you asked for. So the failure has nothing to do with
# the command being run: `ps`, `exec postgres psql`, `config` and `logs` all die
# identically, and a caller that redirects stderr sees only an empty answer.
#
# That is what happened. Deploys 115–118 could not read `platform_settings`,
# failed closed, and skipped the post-deploy journey — four deploys, and the
# error naming the cause was thrown away by `2>/dev/null` for the first three
# (P189-01). `watchdog.sh` has the same load and swallows the same error into
# `|| true`, so its container census counts nothing and reports no problem.
#
# ## Read-only, deliberately
#
# `ds_ensure_secrets` in secrets.sh *generates* what is missing, which is right
# for a deploy and wrong for everything else — a reporting command that quietly
# writes credentials is a reporting command that can be the reason a restore
# does not decrypt. This loader only reads, and refuses by name when a file is
# not there, so a caller gets "secrets.env is not readable" rather than a
# compose interpolation error four layers down (§9.4, §9.6).

# Where the host keeps the two files. `deploy.sh`, `dsc` and `watchdog.sh` each
# had this expression written out; it is one value, so it has one home (§9.10b).
ds_state_dir() { printf '%s' "${DS_STATE_DIR:-${HOME}/ds-education}"; }

# Load both files into the environment, exported, so `docker compose` sees them.
#
# Returns non-zero and says which file, rather than letting the caller discover
# it from compose. Callers that report rather than deploy should treat that as a
# problem to state, never as "nothing is wrong".
ds_load_host_env() {
  local dir config secrets
  dir="$(ds_state_dir)"
  config="${dir}/config.env"
  secrets="${dir}/secrets.env"

  if [ ! -r "$config" ]; then
    echo "xx ${config} is not readable — see infra/deploy/config.env.example" >&2
    return 1
  fi
  # Not optional, and not skipped when absent. A stack whose secrets have never
  # been generated has never been deployed; answering "no problems" about it is
  # the failure this file exists to prevent.
  if [ ! -r "$secrets" ]; then
    echo "xx ${secrets} is not readable — it is generated by deploy.sh on the" \
         "first deploy and never regenerated. Without it docker compose cannot" \
         "interpolate docker-compose.prod.yml, so no command reaches the stack." >&2
    return 1
  fi

  set -a
  # shellcheck disable=SC1090 # runtime paths on the host, not resolvable at lint time
  . "$config"
  # shellcheck disable=SC1090
  . "$secrets"
  set +a

  # And the derived third. `domains.sh` is the one home for these — the same
  # function `deploy.sh` calls — so no caller develops its own idea of what
  # `API_DOMAIN` or `DS_SITES_DIR` is.
  #
  # It exports what it computes, and that is the point: compose substitutes
  # from the process environment, so a value that is only a shell variable
  # interpolates as empty. An empty domain is a warning; an empty bind-mount
  # path is a parse error for the whole file.
  local here
  here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  # shellcheck source=./domains.sh
  . "${here}/domains.sh"
  if ! ds_derive_domains; then
    echo "xx the host domains could not be derived from ${config} — see above." >&2
    return 1
  fi
}
